# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-09 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zx_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anli_name', models.CharField(max_length=30)),
                ('anli_describe', models.TextField(max_length=2000)),
                ('company', models.IntegerField(default=0)),
                ('answer', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('area', models.CharField(choices=[('0-100', '100平米以下'), ('100+', '100平米以上')], max_length=30)),
                ('case_style', models.CharField(choices=[('O', '欧美风格'), ('D', '东方风格')], max_length=30)),
                ('huxing', models.CharField(choices=[('1', '一室一厅'), ('2', '两室两厅'), ('3', '三室两厅'), ('4', '其他')], max_length=30)),
                ('ordinary_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zx_user.Ordinary_User')),
            ],
            options={
                'db_table': 'anli',
            },
            managers=[
                ('cases', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CaseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='anli_images/')),
                ('imageName', models.CharField(default='', max_length=20)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zx_anli.Anli')),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=2000)),
                ('anli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zx_anli.Anli')),
            ],
            options={
                'db_table': 'commments',
            },
        ),
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion', models.TextField(max_length=2000)),
                ('anli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zx_anli.Anli')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zx_user.Company_User')),
            ],
            options={
                'db_table': 'suggestions',
            },
        ),
    ]
