# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-09 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesForDraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images_for_draw/')),
            ],
            options={
                'db_table': 'draw_images',
            },
        ),
    ]
